Repository Nexters/nexters-admin-server, pull requests merged in 2023-02, with the labels that each got.

#1 feat: 초기 엔티티 구축
  build.gradle
  src/main/kotlin/nexters/admin/ServerApplication.kt
  src/main/kotlin/nexters/admin/controller/MemberController.kt
  src/main/kotlin/nexters/admin/domain/attendance/Attendance.kt
  src/main/kotlin/nexters/admin/domain/attendance/AttendanceStatus.kt
  src/main/kotlin/nexters/admin/domain/generation_member/GenerationMember.kt
  src/main/kotlin/nexters/admin/domain/generation_member/Position.kt
  src/main/kotlin/nexters/admin/domain/generation_member/SubPosition.kt
  src/main/kotlin/nexters/admin/domain/session/Session.kt
  src/main/kotlin/nexters/admin/domain/user/Password.kt
  src/main/kotlin/nexters/admin/domain/user/administrator/Administrator.kt
  src/main/kotlin/nexters/admin/domain/user/member/Gender.kt
  src/main/kotlin/nexters/admin/domain/user/member/Member.kt
  src/main/kotlin/nexters/admin/domain/user/member/MemberStatus.kt
  src/main/kotlin/nexters/admin/extensions/StringExtensions.kt
  src/main/kotlin/nexters/admin/repository/MemberRepository.kt
  src/main/kotlin/nexters/admin/service/MemberService.kt
  src/test/kotlin/nexters/admin/ServerApplicationTests.kt
  src/test/kotlin/nexters/admin/domain/user/PasswordTest.kt
Labels: 기능 구현

#3 ci: github actions ci workflow yml 작성
  .github/workflows/ci-backend.yml
Labels: 인프라

#4 feat: 로그인 및 비밀번호 수정 API 구현
  build.gradle
  src/main/kotlin/nexters/admin/controller/MemberController.kt
  src/main/kotlin/nexters/admin/controller/user/MemberController.kt
  src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
  src/main/kotlin/nexters/admin/domain/user/Password.kt
  src/main/kotlin/nexters/admin/domain/user/member/Member.kt
  src/main/kotlin/nexters/admin/exception/CustomExceptions.kt
  src/main/kotlin/nexters/admin/exception/ExceptionControllerAdvice.kt
  src/main/kotlin/nexters/admin/repository/MemberRepository.kt
  src/main/kotlin/nexters/admin/service/MemberService.kt
  src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
  src/main/kotlin/nexters/admin/service/auth/AuthService.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/main/kotlin/nexters/admin/support/auth/AuthAnnotations.kt
  src/main/kotlin/nexters/admin/support/auth/JwtTokenProvider.kt
  src/main/kotlin/nexters/admin/support/auth/LoginUserResolver.kt
  src/main/kotlin/nexters/admin/support/extensions/StringExtensions.kt
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/kotlin/nexters/admin/Fixtures.kt
  src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
  src/test/kotlin/nexters/admin/support/auth/JwtTokenProviderTest.kt
Labels: 기능 구현

#6 feat: springdoc 사용해서 api 문서 생성
  build.gradle
  src/main/kotlin/nexters/admin/config/SwaggerConfig.kt
  src/main/kotlin/nexters/admin/controller/hello/HelloController.kt
  src/main/kotlin/nexters/admin/controller/user/MemberController.kt
  src/main/resources/application.yml
Labels: 문서화

#9 feat: 운영진 직군 정보 및 기타 컬럼 추가
  src/main/kotlin/nexters/admin/domain/generation_member/Position.kt
  src/main/kotlin/nexters/admin/domain/generation_member/SubPosition.kt
  src/main/kotlin/nexters/admin/domain/session/Session.kt
Labels: 기능 구현

#10 feat: 관리자 로그인 API 구현
  src/main/kotlin/nexters/admin/controller/auth/AuthController.kt
  src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
  src/main/kotlin/nexters/admin/domain/user/Password.kt
  src/main/kotlin/nexters/admin/domain/user/administrator/Administrator.kt
  src/main/kotlin/nexters/admin/domain/user/member/Member.kt
  src/main/kotlin/nexters/admin/repository/AdministratorRepository.kt
  src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
  src/main/kotlin/nexters/admin/service/auth/AuthService.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/test/kotlin/nexters/admin/Fixtures.kt
  src/test/kotlin/nexters/admin/domain/user/PasswordTest.kt
  src/test/kotlin/nexters/admin/domain/user/administrator/AdministratorTest.kt
  src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
Labels: API 변경, 기능 구현

#8 feat: 관리자 관련 회원 업무 api 작성
  src/main/kotlin/nexters/admin/config/SwaggerConfig.kt
  src/main/kotlin/nexters/admin/controller/hello/HelloController.kt
  src/main/kotlin/nexters/admin/controller/user/MemberController.kt
  src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
  src/main/kotlin/nexters/admin/domain/generation_member/GenerationMember.kt
  src/main/kotlin/nexters/admin/domain/generation_member/Position.kt
  src/main/kotlin/nexters/admin/domain/generation_member/SubPosition.kt
  src/main/kotlin/nexters/admin/domain/user/administrator/Administrator.kt
  src/main/kotlin/nexters/admin/domain/user/member/Gender.kt
  src/main/kotlin/nexters/admin/domain/user/member/Member.kt
  src/main/kotlin/nexters/admin/domain/user/member/MemberStatus.kt
  src/main/kotlin/nexters/admin/repository/GenerationMemberRepository.kt
  src/main/kotlin/nexters/admin/service/auth/AuthService.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/main/kotlin/nexters/admin/service/user/UserDtos.kt
  src/main/resources/application.yml
  src/test/kotlin/nexters/admin/Fixtures.kt
  src/test/kotlin/nexters/admin/domain/generation_member/GenerationMemberTest.kt
  src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
  src/test/kotlin/nexters/admin/service/auth/AuthServiceTest.kt
  src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
Labels: 테스트, API 변경, 기능 구현

#12 feat: 어드민 API에 대해 인터셉터 추가
  src/main/kotlin/nexters/admin/config/InterceptorConfig.kt
  src/main/kotlin/nexters/admin/controller/auth/AuthController.kt
  src/main/kotlin/nexters/admin/controller/auth/AuthDtos.kt
  src/main/kotlin/nexters/admin/controller/user/MemberController.kt
  src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
  src/main/kotlin/nexters/admin/domain/user/Password.kt
  src/main/kotlin/nexters/admin/domain/user/administrator/Administrator.kt
  src/main/kotlin/nexters/admin/domain/user/member/Member.kt
  src/main/kotlin/nexters/admin/repository/AdminCacheRepository.kt
  src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
  src/main/kotlin/nexters/admin/service/auth/AuthService.kt
  src/main/kotlin/nexters/admin/service/user/AdminService.kt
  src/main/kotlin/nexters/admin/support/auth/AdminAuthInterceptor.kt
  src/main/kotlin/nexters/admin/support/auth/AuthAnnotations.kt
  src/main/kotlin/nexters/admin/support/auth/AuthorizationHeaderUtils.kt
  src/main/kotlin/nexters/admin/support/auth/LoginUserResolver.kt
  src/test/kotlin/nexters/admin/domain/generation_member/GenerationMemberTest.kt
  src/test/kotlin/nexters/admin/domain/user/administrator/AdministratorTest.kt
  src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
  src/test/kotlin/nexters/admin/repository/AdminCacheRepositoryTest.kt
  src/test/kotlin/nexters/admin/service/auth/AuthServiceTest.kt
  src/test/kotlin/nexters/admin/service/user/AdminServiceTest.kt
  src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/ApplicationTest.kt
  src/test/kotlin/nexters/admin/testsupport/DatabaseCleanerCallback.kt
  src/test/kotlin/nexters/admin/testsupport/DatabaseCleanser.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
  src/test/kotlin/nexters/admin/testsupport/RepositoryTest.kt
Labels: 테스트, 기능 구현

#13 feat: prod 구성 디비 연결 설정
  src/main/resources/application-prod.yml
Labels: 인프라

#15 feat: 회원 정보 조회 API 구현
  build.gradle
  src/main/kotlin/nexters/admin/controller/attendance/AttendanceController.kt
  src/main/kotlin/nexters/admin/controller/user/MemberController.kt
  src/main/kotlin/nexters/admin/domain/attendance/Attendance.kt
  src/main/kotlin/nexters/admin/domain/attendance/AttendanceStatus.kt
  src/main/kotlin/nexters/admin/exception/CustomExceptions.kt
  src/main/kotlin/nexters/admin/repository/AttendanceRepository.kt
  src/main/kotlin/nexters/admin/repository/GenerationMemberRepository.kt
  src/main/kotlin/nexters/admin/repository/SessionRepository.kt
  src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
  src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
  src/main/kotlin/nexters/admin/service/user/MemberDtos.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
  src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 기능 구현

#22 fix: enum 서버 에러 대신 커스텀 예외 반환하도록 구현
  src/main/kotlin/nexters/admin/domain/generation_member/Position.kt
  src/main/kotlin/nexters/admin/domain/generation_member/SubPosition.kt
  src/main/kotlin/nexters/admin/domain/user/member/Gender.kt
  src/main/kotlin/nexters/admin/domain/user/member/MemberStatus.kt
  src/main/kotlin/nexters/admin/exception/CustomExceptions.kt
  src/test/kotlin/nexters/admin/domain/generation_member/PositionTest.kt
  src/test/kotlin/nexters/admin/domain/generation_member/SubPositionTest.kt
  src/test/kotlin/nexters/admin/domain/user/member/GenderTest.kt
  src/test/kotlin/nexters/admin/domain/user/member/MemberStatusTest.kt
Labels: 버그 수정

#24 fix: 내 출석 정보 조회 시 관리자 인가가 필요하지 않도록 변경
  src/main/kotlin/nexters/admin/config/InterceptorConfig.kt
Labels: 버그 수정

#31 feat: DB에서 is_manager 컬럼 제거
  src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
  src/main/kotlin/nexters/admin/domain/generation_member/GenerationMember.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/main/kotlin/nexters/admin/service/user/UserDtos.kt
  src/test/kotlin/nexters/admin/domain/generation_member/GenerationMemberTest.kt
  src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 기능 수정

#14 [개발중] feat: 세션, 기수 api
  src/main/kotlin/nexters/admin/controller/generation/GenerationController.kt
  src/main/kotlin/nexters/admin/controller/session/SessionController.kt
  src/main/kotlin/nexters/admin/domain/generation/Generation.kt
  src/main/kotlin/nexters/admin/domain/generation/GenerationStatus.kt
  src/main/kotlin/nexters/admin/exception/CustomExceptions.kt
  src/main/kotlin/nexters/admin/repository/GenerationRepository.kt
  src/main/kotlin/nexters/admin/service/generation/GenerationDtos.kt
  src/main/kotlin/nexters/admin/service/generation/GenerationService.kt
  src/main/kotlin/nexters/admin/service/session/SessionDtos.kt
  src/main/kotlin/nexters/admin/service/session/SessionService.kt
  src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
Labels: 기능 구현

#35 config: CORS 셋업 및 preflight 요청 대응
  src/main/kotlin/nexters/admin/config/CorsConfig.kt
  src/main/kotlin/nexters/admin/support/auth/AdminAuthInterceptor.kt
Labels: 설정 변경

#25 test: 인수테스트 기본 틀 작성
  build.gradle
  src/main/kotlin/nexters/admin/repository/AdminCacheRepository.kt
  src/test/kotlin/nexters/admin/acceptance/AcceptanceFixtures.kt
  src/test/kotlin/nexters/admin/acceptance/MemberAcceptanceTest.kt
  src/test/kotlin/nexters/admin/testsupport/AcceptanceTest.kt
  src/test/kotlin/nexters/admin/testsupport/DatabaseCleanser.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
  src/test/kotlin/nexters/admin/testsupport/RepositoryTest.kt
Labels: 테스트

#38 refactor: SessionDto Controller/Service 레이어 분리
  src/main/kotlin/nexters/admin/controller/session/SessionController.kt
  src/main/kotlin/nexters/admin/controller/session/SessionDtos.kt
  src/main/kotlin/nexters/admin/service/session/SessionDtos.kt
  src/main/kotlin/nexters/admin/service/session/SessionService.kt
  src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
Labels: 리팩터링

#26 feat: QR 코드 및 출석 처리 API 구현
  src/main/kotlin/nexters/admin/config/SchedulerConfig.kt
  src/main/kotlin/nexters/admin/config/TimeZoneConfig.kt
  src/main/kotlin/nexters/admin/controller/attendance/AttendanceController.kt
  src/main/kotlin/nexters/admin/controller/attendance/AttendanceDtos.kt
  src/main/kotlin/nexters/admin/domain/attendance/Attendance.kt
  src/main/kotlin/nexters/admin/domain/attendance/AttendanceStatus.kt
  src/main/kotlin/nexters/admin/domain/attendance/QrCode.kt
  src/main/kotlin/nexters/admin/exception/CustomExceptions.kt
  src/main/kotlin/nexters/admin/repository/AttendanceRepository.kt
  src/main/kotlin/nexters/admin/repository/QrCodeRepository.kt
  src/main/kotlin/nexters/admin/scheduler/QrScheduler.kt
  src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
  src/main/kotlin/nexters/admin/service/attendance/QrCodeService.kt
  src/main/kotlin/nexters/admin/support/utils/RandomUtils.kt
  src/test/kotlin/nexters/admin/domain/attendance/QrCodeTest.kt
  src/test/kotlin/nexters/admin/repository/QrCodeRepositoryTest.kt
  src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
  src/test/kotlin/nexters/admin/service/attendance/QrCodeServiceTest.kt
  src/test/kotlin/nexters/admin/support/utils/RandomUtilsKtTest.kt
  src/test/kotlin/nexters/admin/testsupport/DatabaseCleanser.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
  src/test/kotlin/nexters/admin/testsupport/RepositoryTest.kt
Labels: 기능 구현

#37 feat: kotlin 관련 swagger 의존성 추가
  build.gradle
Labels: 문서화

#39 feat: 메인 세션 조회 api 구현
  src/main/kotlin/nexters/admin/controller/session/SessionController.kt
  src/main/kotlin/nexters/admin/domain/session/SessionStatus.kt
  src/main/kotlin/nexters/admin/repository/AttendanceRepository.kt
  src/main/kotlin/nexters/admin/repository/SessionRepository.kt
  src/main/kotlin/nexters/admin/service/session/SessionDtos.kt
  src/main/kotlin/nexters/admin/service/session/SessionService.kt
  src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/DatabaseCleanser.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 기능 구현

#34 feat: CSV 파일 기반 회원 복수 생성 API 구현
  build.gradle
  src/main/kotlin/nexters/admin/controller/user/MemberController.kt
  src/main/kotlin/nexters/admin/domain/generation_member/GenerationMember.kt
  src/main/kotlin/nexters/admin/domain/generation_member/GenerationMembers.kt
  src/main/kotlin/nexters/admin/domain/generation_member/Position.kt
  src/main/kotlin/nexters/admin/domain/generation_member/SubPosition.kt
  src/main/kotlin/nexters/admin/domain/user/member/Member.kt
  src/main/kotlin/nexters/admin/domain/user/member/Members.kt
  src/main/kotlin/nexters/admin/exception/CustomExceptions.kt
  src/main/kotlin/nexters/admin/repository/GenerationMemberRepository.kt
  src/main/kotlin/nexters/admin/repository/MemberRepository.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/main/kotlin/nexters/admin/support/utils/CsvParseUtils.kt
  src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
  src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
  src/test/kotlin/nexters/admin/support/utils/CsvParseUtilsKtTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
  src/test/resources/testdata.csv
Labels: 기능 구현

#40 fix: 일반 회원 기능들이 동작하지 않던 버그를 수정한다
  src/main/kotlin/nexters/admin/config/WebMvcConfig.kt
  src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
  src/test/kotlin/nexters/admin/acceptance/MemberAcceptanceTest.kt
Labels: 버그 수정, 테스트

#43 fix: 초기 비밀번호 길이 제한을 변경한다
  src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
  src/main/kotlin/nexters/admin/domain/user/member/Member.kt
  src/test/kotlin/nexters/admin/acceptance/AcceptanceFixtures.kt
  src/test/kotlin/nexters/admin/acceptance/MemberAcceptanceTest.kt
Labels: API 변경

#45 fix: open session in view 설정 적용
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/kotlin/nexters/admin/acceptance/AcceptanceFixtures.kt
  src/test/kotlin/nexters/admin/acceptance/MemberAcceptanceTest.kt
Labels: 버그 수정, 설정 변경

#48 feat: Spring Bean Validation 추가
  src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
  src/main/kotlin/nexters/admin/exception/ExceptionControllerAdvice.kt
  src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
  src/test/kotlin/nexters/admin/acceptance/MemberAcceptanceTest.kt
Labels: 기능 구현

#41 refactor: 세션 서비스 테스트코드 리팩토링
  src/main/kotlin/nexters/admin/service/session/SessionService.kt
  src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
Labels: 테스트, 리팩터링

#47 refactor: session 관련 도메인이 아닌 dto를 반환하도록 변경
  src/main/kotlin/nexters/admin/controller/session/SessionController.kt
  src/main/kotlin/nexters/admin/service/session/SessionDtos.kt
  src/main/kotlin/nexters/admin/service/session/SessionService.kt
  src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
Labels: 리팩터링

#54 fix: Swagger에서 csv 파일 업로드할 수 있도록 API에 설정 추가
  src/main/kotlin/nexters/admin/controller/user/MemberController.kt
Labels: 문서화

#52 fix: 기수 생성이 되지 않던 버그를 수정한다
  src/main/kotlin/nexters/admin/controller/generation/GenerationController.kt
  src/main/kotlin/nexters/admin/controller/generation/GenerationDtos.kt
  src/main/kotlin/nexters/admin/domain/generation/Generation.kt
  src/main/kotlin/nexters/admin/domain/generation/GenerationStatus.kt
  src/main/kotlin/nexters/admin/exception/CustomExceptions.kt
  src/main/kotlin/nexters/admin/repository/GenerationMemberRepository.kt
  src/main/kotlin/nexters/admin/repository/GenerationRepository.kt
  src/main/kotlin/nexters/admin/repository/MemberRepository.kt
  src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
  src/main/kotlin/nexters/admin/service/generation/GenerationDtos.kt
  src/main/kotlin/nexters/admin/service/generation/GenerationService.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/test/kotlin/nexters/admin/acceptance/GenerationAcceptanceTest.kt
  src/test/kotlin/nexters/admin/acceptance/MemberAcceptanceTest.kt
  src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
  src/test/kotlin/nexters/admin/service/generation/GenerationServiceTest.kt
  src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 버그 수정, 문서화, 테스트, API 변경, 기능 구현, 기능 수정

#51 feat: 존재하지 않는 회원 수정 및 삭제 시도시 404 반환
  src/main/kotlin/nexters/admin/controller/user/MemberController.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/test/kotlin/nexters/admin/acceptance/MemberAcceptanceTest.kt
  src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 기능 수정

#53 fix: LocalDateTime Json 응답값 포매팅
  src/main/kotlin/nexters/admin/controller/attendance/AttendanceDtos.kt
  src/main/kotlin/nexters/admin/domain/user/administrator/Administrator.kt
  src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
  src/main/kotlin/nexters/admin/service/session/SessionDtos.kt
Labels: 기능 구현

#59 fix: 회원 복수 생성 시, 기수가 이미 있으면 중복생성하지 않도록 수정
  src/main/kotlin/nexters/admin/controller/user/MemberController.kt
  src/main/kotlin/nexters/admin/domain/generation_member/GenerationMembers.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
Labels: 리팩터링, 기능 수정

#61 fix: session 도메인 일부 칼럼 not null 처리 및 새로운 세션 생성시 회원 출석 정보 생성
  src/main/kotlin/nexters/admin/controller/session/SessionDtos.kt
  src/main/kotlin/nexters/admin/domain/session/Session.kt
  src/main/kotlin/nexters/admin/service/session/SessionDtos.kt
  src/main/kotlin/nexters/admin/service/session/SessionService.kt
  src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 버그 수정, 기능 수정

#66 feat: 기수 회원 등록시 출석 정보 추가 기능 구현
  src/main/kotlin/nexters/admin/repository/SessionRepository.kt
  src/main/kotlin/nexters/admin/service/user/MemberService.kt
  src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 기능 구현

#68 fix: 세션 속성 네이밍 변경 및 dto optional 여부 수정
  src/main/kotlin/nexters/admin/controller/session/SessionDtos.kt
  src/main/kotlin/nexters/admin/domain/session/Session.kt
  src/main/kotlin/nexters/admin/repository/SessionRepository.kt
  src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
  src/main/kotlin/nexters/admin/service/session/SessionDtos.kt
  src/main/kotlin/nexters/admin/service/session/SessionService.kt
  src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 기능 수정

#64 feat: 출석 정보들을 조회하는 기능 구현
  src/main/kotlin/nexters/admin/controller/attendance/AttendanceController.kt
  src/main/kotlin/nexters/admin/domain/attendance/Attendance.kt
  src/main/kotlin/nexters/admin/domain/attendance/AttendanceStatus.kt
  src/main/kotlin/nexters/admin/domain/session/Session.kt
  src/main/kotlin/nexters/admin/exception/CustomExceptions.kt
  src/main/kotlin/nexters/admin/repository/AttendanceRepository.kt
  src/main/kotlin/nexters/admin/repository/GenerationMemberRepository.kt
  src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
  src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
  src/main/kotlin/nexters/admin/service/attendance/QrCodeService.kt
  src/test/kotlin/nexters/admin/acceptance/AcceptanceFixtures.kt
  src/test/kotlin/nexters/admin/acceptance/AttendanceAcceptanceTest.kt
  src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
  src/test/kotlin/nexters/admin/service/attendance/QrCodeServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 테스트, 기능 구현

#65 feat: 출결 상태 수정 API 구현 및 출석 점수 자동 업데이트 구현
  src/main/kotlin/nexters/admin/controller/attendance/AttendanceController.kt
  src/main/kotlin/nexters/admin/controller/attendance/AttendanceDtos.kt
  src/main/kotlin/nexters/admin/domain/attendance/Attendance.kt
  src/main/kotlin/nexters/admin/domain/attendance/AttendanceStatus.kt
  src/main/kotlin/nexters/admin/domain/generation_member/GenerationMember.kt
  src/main/kotlin/nexters/admin/exception/CustomExceptions.kt
  src/main/kotlin/nexters/admin/repository/AttendanceRepository.kt
  src/main/kotlin/nexters/admin/repository/SessionRepository.kt
  src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
  src/test/kotlin/nexters/admin/acceptance/AcceptanceFixtures.kt
  src/test/kotlin/nexters/admin/acceptance/AttendanceAcceptanceTest.kt
  src/test/kotlin/nexters/admin/domain/attendance/AttendanceTest.kt
  src/test/kotlin/nexters/admin/domain/generation_member/GenerationMemberTest.kt
  src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
  src/test/kotlin/nexters/admin/testsupport/Fixtures.kt
Labels: 기능 구현
